name: panvimdoc

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'
      - 'lua/**/*.lua'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: macrobank
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain doc/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-update help from README [skip ci]"
          file_pattern: doc/*.txt