name: panvimdoc

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: macrobank
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto-update documentation"
          file_pattern: doc/*.txt